Repository johannesgrothe/Smarthome_System, pull requests merged in 2021-12, with the labels that each got.

#7 #6 Add basic workflows
  .github/workflows/repo_checks.yml
  .github/workflows/tests.yml
  Pipfile
  pytest.ini
  tests/test_schemas.py
Labels: repository

#10 #9 Replaced "name" field with "id"
  json_schemas/api_gadget_data.json
Labels: bug

#14 Fb 12 wiki export workflow
  .github/workflows/repo_checks.yml
  .github/workflows/wiki_export.yml
  api_docs/export_api_docs.py
Labels: repository

#16 #15 Added missing python setup
  .github/workflows/wiki_export.yml
Labels: bug, repository

#18 #17 Fix wiki export pipeline not using pipenv
  .github/workflows/wiki_export.yml
Labels: bug, repository

#20 #19 Changed github user settings
  .github/workflows/wiki_export.yml
Labels: enhancement

#23 #22 Removed gadget sync from api
  api_docs/api_specs.json
  api_params.h
  api_params.py
Labels: documentation

#25 Fb 24 add gadget docs
  .github/workflows/wiki_export.yml
  __init__.py
  api_docs/export_api_constants.py
  api_docs/script_params.py
  api_params.h
  api_params.py
  export.py
  exporters/api_constants_exporter.py
  exporters/api_doc_exporter.py
  exporters/constants_exporter.py
  exporters/definitions_loader.py
  exporters/doc_exporter.py
  exporters/gadget_constants_exporter.py
  exporters/gadget_doc_exporter.py
  exporters/script_params.py
  exporters/temp_dir_manager.py
  gadget_definitions.h
  gadget_definitions.py
  gadget_docs/gadget_specs.json
  gadget_docs/gadget_specs_schema.json
  lib/system_identifier.py
  tests/test_exported_files.py
  tests/test_system_identifier.py
  utils/markdown_file.py
Labels: documentation, enhancement

#26 Fb 8 add api version
  .github/workflows/pr_tests.yml
  api_definitions.h
  api_definitions.py
  api_docs/api_specs.json
  api_docs/api_specs_schema.json
  api_params.h
  api_params.py
  exporters/api_constants_exporter.py
  exporters/api_doc_exporter.py
  exporters/gadget_constants_exporter.py
  exporters/script_params.py
  exporters/temp_dir_manager.py
  gadget_definitions.h
  gadget_definitions.py
  tests/conftest.py
  tests/cpp_compile_test.cpp
  tests/test_api_version_incrementation.py
  tests/test_exported_files_integrity.py
  tests/test_exported_files_recency.py
  tests/test_software_version.py
  tests/test_system_identifier.py
  utils/software_version.py
  utils/system_identifier.py
Labels: documentation

#27 Fb 21 add link to constants file to api docs
  exporters/api_doc_exporter.py
  exporters/doc_exporter.py
  exporters/gadget_doc_exporter.py
  exporters/script_params.py
  utils/markdown_file.py
Labels: documentation

#29 Fb 28 extended gadget config
  api_definitions.h
  api_definitions.py
  api_docs/api_specs.json
  exporters/gadget_doc_exporter.py
  gadget_docs/gadget_specs.json
  gadget_docs/gadget_specs_schema.json
  json_schemas/client_gadget_config.json
Labels: documentation

#32 #31 Added new API paths to system submodule
  api_definitions.h
  api_definitions.py
  api_docs/api_specs.json
  json_schemas/api_config_delete_get.json
  json_schemas/api_config_get_all_response.json
  json_schemas/api_config_get_response.json
  json_schemas/api_config_save.json
  json_schemas/client_config.json
Labels: enhancement

#34 #33 Made repo checks primary-branch independent
  .github/workflows/repo_checks.yml
Labels: enhancement
