Repository johannesgrothe/Smarthome_System, pull requests merged in 2022-02, with the labels that each got.

#50 Fb 49 add access level api
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  api_docs/api_specs_schema.json
  exporters/api_constants_exporter.py
  exporters/script_params.py
Labels: enhancement

#60 Fb 57 persistent users file
  json_schemas/bridge_persistent_users.json
Labels: enhancement

#58 Fb 54 split api doc
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  api_docs/api_specs_schema.json
  export.py
  exporters/api_constants_exporter.py
  exporters/api_doc_exporter.py
  exporters/doc_exporter.py
Labels: enhancement

#61 Fb 53 access level documentation
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  exporters/api_doc_exporter.py
  utils/markdown_file.py
Labels: documentation

#62 Fb 55 read write access
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  api_docs/api_specs_schema.json
  exporters/api_doc_exporter.py
Labels: documentation

#63 Fb 56 rebuild python api constants
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  export.py
  exporters/api_constants_exporter.py
  exporters/script_params.py
  tests/test_doc_exporters.py
  utils/api_endpoint_definition.py
Labels: documentation, enhancement

#65 Fb 64 uti to api def
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  exporters/api_constants_exporter.py
  exporters/script_params.py
  utils/api_endpoint_definition.py
Labels: enhancement
