Repository johannesgrothe/Smarthome_System, pull requests merged in 2022-01, with the labels that each got.

#37 Fb 30 code generator classes
  api_definitions.h
  exporters/api_constants_exporter.py
  exporters/constants_exporter.py
  exporters/gadget_constants_exporter.py
  exporters/script_params.py
  gadget_definitions.h
  utils/cpp_file.py
Labels: documentation

#36 #35 Added history check script
  .github/workflows/repo_checks.yml
Labels: repository

#41 #40 CPP problems
  api_definitions.h
  exporters/api_constants_exporter.py
  exporters/gadget_constants_exporter.py
  gadget_definitions.h
Labels: bug

#42 Fb 38 add js file generator
  api_definitions.js
  export.py
  exporters/api_constants_exporter.py
  exporters/constants_exporter.py
  exporters/gadget_constants_exporter.py
  exporters/script_params.py
  gadget_definitions.js
  tests/test_exported_files_integrity.py
  tests/test_exported_files_recency.py
  utils/js_file.py
Labels: enhancement

#45 #44 Added the paths to api_specs, created new response
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  json_schemas/api_bridge_update_check_response.json
Labels: enhancement

#46 Fb 43 api version
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  json_schemas/api_client_data.json
Labels: documentation

#48 #47 Deleted file
  json_schemas/bridge_gadget_update_request.json
Labels: bug

#52 Fb 51 api version regex
  api_definitions.h
  api_definitions.js
  api_definitions.py
  api_docs/api_specs.json
  json_schemas/api_client_data.json
Labels: bug
